variables:
  SRC_REPOSITORY: https://git.thm.de/arsnova/arsnova-mobile.git
  MIRROR_REPOSITORY: git@github.com:thm-projects/arsnova-mobile.git
  WAR_FILE: target/arsnova-mobile.war

stages:
  - analysis
  - build
  - deploy
  - synchronization

sync_mirror:
  stage: synchronization
  when: always
  allow_failure: true
  script:
    - git clone --bare $SRC_REPOSITORY mirror.git
    - cd mirror.git
    - git update-ref -d refs/tags/production
    - git update-ref -d refs/tags/staging
    - git push --mirror $MIRROR_REPOSITORY

jshint:
  stage: analysis
  tags:
    - nodejs
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt jshint

jscs:
  stage: analysis
  tags:
    - nodejs
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt jscs

package:
  stage: build
  tags:
    - nodejs
    - sencha
  artifacts:
    paths:
      - $WAR_FILE
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt package

tomcat_production:
  stage: deploy
  only:
    - production
  script:
    - curl --upload-file $WAR_FILE https://$PROD_TOMCAT_USER:$PROD_TOMCAT_PASSWORD@$PROD_TOMCAT_HOST/manager/deploy?path=%2Fmobile

tomcat_development:
  stage: deploy
  only:
    - staging
  script:
    - curl --upload-file $WAR_FILE https://$DEV_TOMCAT_USER:$DEV_TOMCAT_PASSWORD@$DEV_TOMCAT_HOST/manager/deploy?path=%2Fmobile
