# Note: YAML does not allow Tabs for indentation!

language: node_js
before_install:
  - "npm install -g grunt-cli"
script:
  # Run code style checks
  - "grunt jscs"
notifications:
  slack: f112a:GOZb6ewuAf2AVxduDXzdiCTG
  email: admin@arsnova.eu

addons:
  sauce_connect: true
