# Note: YAML does not allow Tabs for indentation!

language: java
env:
  global:
  - ARSNOVA_SENCHA_CMD_VERSION="4.0.4.84"
  # Sauce Labs
  - secure: "a40mKptMrfdsTkbtbXRfhUd68nWoQXIgEBEimg2xcpwE39j63Xb7YljotecjBBUgpHqZz0/dr8i5qgYqOk+SBXdpYtwOsGJ7SM3tTdb+cYnxPw5Br3YfK2GQwZXkgm6U2F3aDTKt/cZqTyfFI0cQok//vt7GPykF6Ieoh023dUM="
  - secure: "A1tAwqHLhSDa/yAthaq5MKYCjSHU/Z5wuc/znIklgmqd0GLYQ25T+huTPn9Kh9LuFOsbVGFRJk/ydRxAAQtAUdcHaY38xjspxkznP3osd2QtDVGgLLGv02RfcIorWOwIOKR8jWgsQv5cuAD+u8/baNzkdDD0abvBGlNVCNYNLxg="
  matrix:
    - "BROWSER='firefox::Windows 7'"
    - "BROWSER='chrome::Windows 7'"
    - "BROWSER='internet_explorer::Windows 7'"
    - "BROWSER='opera::Windows 7'"
services:
  - couchdb
before_install:
  # Install Sencha Command (taken from deftjs/DeftJS)
  - "wget http://cdn.sencha.com/cmd/$ARSNOVA_SENCHA_CMD_VERSION/SenchaCmd-$ARSNOVA_SENCHA_CMD_VERSION-linux-x64.run.zip"
  - "unzip -q SenchaCmd-$ARSNOVA_SENCHA_CMD_VERSION-linux-x64.run.zip"
  - "chmod +x SenchaCmd-$ARSNOVA_SENCHA_CMD_VERSION-linux-x64.run"
  - "./SenchaCmd-$ARSNOVA_SENCHA_CMD_VERSION-linux-x64.run --mode unattended"
  # Configure Sencha, add to PATH
  - "echo 'build.options.custom=selenium:true' > ~/bin/Sencha/Cmd/sencha.cfg"
  - "export PATH=~/bin/Sencha/Cmd/$ARSNOVA_SENCHA_CMD_VERSION/:$PATH"
  # Download ARSnova-war, CouchDB init
  - "git clone https://github.com/thm-projects/arsnova-war"
  - "git clone https://github.com/thm-projects/setuptool"
  # Install tools required for GUI testing
  - "gem install selenium-webdriver"
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
install:
  # Download dependencies, install packages, run server
  - "mvn install"
  - "cd arsnova-war"
  - "mvn install -DskipTests=true"
  - "mvn jetty:run -Dmobile.path=../src/main/webapp/build/production/ARSnova/ &"
  - "sleep 30"
  - "cd .."
before_script:
  # Setup CouchDB
  - "sudo mkdir /etc/arsnova"
  - "sudo cp arsnova-war/src/main/webapp/arsnova.properties.example /etc/arsnova/arsnova.properties"
  - "cd setuptool"
  - "python tool.py"
  - "cd .."
script:
  # Run tests
  - "ruby src/test/saucelabs.rb"
notifications:
  slack: f112a:GOZb6ewuAf2AVxduDXzdiCTG
  email: admin@ecollab.eu

addons:
  sauce_connect: true
